### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [AyanMeow/FluffB#1]
.

**Comment by AyanMeow** [comment]
> 看了你的代码，有一些问题想要交流，最近也在学习这块，能否留个联系方式？

可以在这里直接讨论，我会每天查看github的

**Comment by dsfhoewf** [comment]
大佬有考虑过fuzz这块的随机数据，加入一些AFL遗传算法之类的东西吗，就比如根据被测设备的响应状态和日志（能获取到的话），来不断的修改当前fuzz的数据和优先级之类的？还有关于fuzz bt/ble这块，看你写了很多种方式，问下有推介的论文或者文章之类的吗，我也去学习下这样。

**Comment by AyanMeow** [comment]
> 大佬有考虑过fuzz这块的随机数据，加入一些AFL遗传算法之类的东西吗，就比如根据被测设备的响应状态和日志（能获取到的话），来不断的修改当前fuzz的数据和优先级之类的？还有关于fuzz bt/ble这块，看你写了很多种方式，问下有推介的论文或者文章之类的吗，我也去学习下这样。

方案进行到后半段的时候有考虑过加入遗传算法来解决，但是实验一段时间后发现偏底层的协议，诸如L2CAP，RAF这种，它的反馈几乎是可有可无的，L2CAP虽然存在状态机，但从攻击者的角度是没有办法很准确、及时确定目标所处状态的，加上蓝牙连接范围不算广和稳定。
OBEX协议倒是应该可以使用，但是因为时间问题没有进行过多的尝试，同时，OBEX的安全机制也要更加完善一些，在更早的一些协议版本里成功的概率会要大一些。相关的论文的话，可以看看《The Relevance of Classic Fuzz Testing:Have We Solved This One?》，《Fuzz-Web: A Methodology Based on Fuzzy Logic for Assessing Web Sites》，《OPTIMIZING WEB APPLICATION FUZZING WITH GENETIC ALGORITHMSAND LANGUAGE THEORY》，《基于深度学习的软件安全漏洞挖掘》，《基于遗传算法和Fuzzin...术的Web应用漏洞挖掘研究_张思聪》，蓝牙相关的论文确实很少:(，很多时候都触类旁通

**Comment by dsfhoewf** [comment]
感谢指点，刷了个dongle，准备尝试下ble的脚本了。
看大佬的文档里有出现fuzz_pcap.py，但是在源码里没看到，是没上传吗？

**Comment by dsfhoewf** [comment]
还有，这一版ble的代码里，是不是并没有实现检测crash的逻辑？
看起来只是打印，并没有检测广播之类的。。。
![image](https://user-images.githubusercontent.com/28263125/228809924-8f86ea3b-fc6b-4db0-9392-961f8a279e22.png)

**Comment by AyanMeow** [comment]
> 感谢指点，刷了个dongle，准备尝试下ble的脚本了。 看大佬的文档里有出现fuzz_pcap.py，但是在源码里没看到，是没上传吗？

事实上，这一部分不由我本人负责，它在开发过程中可能确实是缺省了。我上传了一部分说明书，希望能够帮到你

**Comment by dsfhoewf** [comment]
论文拜读了，感谢大佬分享。

**Comment by dsfhoewf** [comment]
运行环境：
kali2022.3
csr4.0
这几天尝试运行了下传统蓝牙这块的功能，obex dos，发现了一个问题，在执行到connect连接蓝牙设备的时候，总是提示超时（timeout），或者连接被拒绝(connect refuse)不能连接成功，kali上运行多次，只有一次弹出了配对的提示，想问下大佬之前是怎么处理这块问题的？

**Comment by ghost** [comment]
.
